### ISSUE TITLE
Mod Compatability

### ISSUE THREAD

**Issue by skellitor301** [elytra/Albedo#21] opened 2019-01-26 20:30 UTC
Quick question, would this mod also be compatible with other mods that have colored lights such as Project Red? I'm a big fan of Project Red and would love to have the colored lights emit their colors. I've tried looking around for answers and I've come up dry. Sorry for opening an issue for a question, just couldn't find a good way to ask this otherwise.

**Comment by exaskye** [comment] 2019-01-26 20:31
Mirage provides dynamic lights, not static lights. Attempts to use it for many static lights will result in lag.

Effectively a duplicate of #7

**Closed as completed by exaskye** 2019-01-26 20:31 UTC

**Comment by exaskye** [comment] 2019-01-26 20:32
Also note Mirage is more or less unmaintained at this point, especially by me. I think the Mystic Mods team is maintaining a fork of Mirage or Albedo, but I'm not entirely sure.

**Comment by skellitor301** [comment] 2019-01-27 18:47
The hunt continues then for colored light support for PR, thanks for the assist

**Comment by falkreon** [comment] 2019-01-27 19:47
Technically the ProjectRed people could add support for Mirage, Albedo, or both; any TileEntity can declare a colored light for either mod (in Mirage, multiple lights). But that would be on ProjectRed to do, and I doubt they have interest in either unmaintained mod.

The MysticMods team which obtained Albedo reached out about combining the mods. I gave them permission on behalf of the team and would honestly love to see a unified colored lights approach, but it's a difficult problem and a hard mod to maintain, so I'm not surprised if there's nothing to announce yet.

There's some promising motion in Fabric for wilder graphical tweaks like this; some day I'd love to take up a MogMiner / SpaceToaster approach and make static, obstructable colored lights happen, but for now, yeah, the hunt continues.
